#FROM node:alpine

FROM alpine

RUN apk add --update mc
RUN apk add npm

WORKDIR '/app'

COPY package.json .

RUN npm install

RUN npm install --save normalize-path

#RUN npm install -g create-react-app

COPY . .

CMD ["npm", "run", "start"]