version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - /app/node_modules # keep this as on immage
      - .:/app # map local . to /app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # keep this as on immage
      - .:/app # map local . to /app
    command: ["npm", "run", "test"]